cache:
  untracked: true
  key: $CI_COMMIT_REF_NAME
  paths:
    - .yarn-cache/

stages:
  - setup
  - test
  - build
  - release

setup:
  stage: setup
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules/
  artifacts:
    expire_in: 3d
    paths:
      - node_modules
  script:
    - yarn install --pure-lockfile --cache-folder .yarn-cache

lint:
  stage: test
  cache:
    policy: pull
  script:
    - yarn lint

test:
  stage: test
  cache:
    policy: pull
  script:
    - cp .env.example .env
    - yarn test

test-poa:
  stage: test
  cache:
    policy: pull
  script:
    - cp .env.example .env
    - yarn test:poa

test-poa-proxy:
  stage: test
  cache:
    policy: pull
  script:
    - cp .env.example .env
    - yarn test:poa-proxy

# test-frozen:
#   stage: test
#   cache:
#     policy: pull
#   script:
#     - yarn test:frozen

# mythril:
#   stage: test
#   cache:
#     policy: pull
#   script:
#     - yarn truffle compile
#     - /opt/python3/bin/python3 /opt/mythril/myth --truffle

build:
  stage: build
  cache:
    policy: pull
  script:
    - cat .env.example > .env
    - yarn build

release:
  stage: release
  cache:
    policy: pull
  only:
    - master
  script:
    - /bin/sh $(pwd)/scripts/ci-release.sh
