cache:
  untracked: true
  key: $CI_COMMIT_REF_NAME
  paths:
    - .yarn-cache/

stages:
  - setup
  - test
  - release

#########
# SETUP #
#########
setup:
  stage: setup
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules/
  artifacts:
    expire_in: 3d
    paths:
      - node_modules
  script:
    - yarn install --pure-lockfile --cache-folder .yarn-cache

########
# TEST #
########
lint:
  stage: test
  cache:
    policy: pull
  script:
    - yarn lint

test:
  stage: test
  cache:
    policy: pull
  script:
    - cp .env.example .env
    - yarn test:ci

# test-frozen:
#   stage: test
#   cache:
#     policy: pull
#   script:
#     - yarn test:frozen

# mythril:
#   stage: test
#   cache:
#     policy: pull
#   script:
#     - yarn truffle compile
#     - /opt/python3/bin/python3 /opt/mythril/myth --truffle

###############
# NPM RELEASE #
###############
release:
  stage: release
  cache:
    policy: pull
  only:
    - master
  script:
    - /bin/sh $(pwd)/scripts/ci-release.sh
